### PR TITLE
Passing errors via callback, accepting headers for the request

### PR DESCRIPTION
**Pull request by sidsakhadeo**
- Creating request object from path (if string)
- Accepting headers in the request object
- Sample request object passed from user: 

```
{
            path: '/sch/i.html?_nkw=handbag&warmup=true',
            headers: {
                'User-Agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4',
                'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp',
                'Accept-Encoding': 'gzip, deflate, sdch'
            }
        }
```
- Passing err to user

### CODE REVIEW

**Comment by sidsakhadeo** [comment]
Thanks!

**Comment by patrick-steele-idem** [comment]
Thank you! I just realized you didn't add any tests or update the README.md. Is that something you could also work on as a separate PR? Thanks again.

**Comment by sidsakhadeo** [comment]
Yeah, what I was thinking of (and I should have mentioned this earlier) is to pull the new version of this module and deploy and test it in a production environment. Just to make sure everything is running okay. As soon as that works fine, I will update the README and add test cases, I promise. :)

**Comment by patrick-steele-idem** [comment]
> Just to make sure everything is running okay

Isn't that what tests are for? :)

**Comment by sidsakhadeo** [comment]
Right, I get your point. Let me get started on the tests. Sorry about that.

**Comment by patrick-steele-idem** [comment]
No worries! I'm very glad to see this feature enhancement. Thank you for working on this.

**Pull request merged**
