### PR TITLE
Fixed failing test

### PR DESCRIPTION
**Pull request by sidsakhadeo**
Updated the test to check for the request object. Let me know if this works.

### CODE REVIEW

**Comment by sidsakhadeo** [comment]
Does this look good?

**Comment by sidsakhadeo** [comment]
Thanks!

**Comment by patrick-steele-idem** [comment]
I still don't where you are testing the new ability to set headers, but it is no worse than before... Also, if you are going to add a new option (such as "headers"), an example should be added into the `Usage` section of the README.md. I will publish for now, but if you have time to update the docs and tests that would be great. Thanks.

**Comment by patrick-steele-idem** [comment]
New version published: `warmup@1.1.0`

**Comment by sidsakhadeo** [comment]
Sorry this is my first time contributing to a project on Github. I realize my work is not really polished.

Regarding the example for usage, I had added one here:

```
{
            path: '/baz', // Required
            headers: {
                'User-Agent': 'xxx'
            }
}
```

Is this a good example?

For the test for headers, currently the warmup tasks can be passed as a string (path of the request) or an object which specifies the path and a headers property. The bare minimum requirement for passing information as an object is the `path` property which I check for. We append the `http://localhost:<port>` to it and pass it to the `request(options, callback)`. Arguably, this can be done by just passing the path as a string but it is still a valid use case. I can add a check for the `headers` property but this object can contain other properties like oauth, json, etc and the user can pass these directly as a warmup task. So I was a bit skeptical of testing just that the `headers` property is filled. What do you think?

**Pull request merged**
